;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ace-window
	org-delete-char
	org-self-insert-command
	reactivate-mark
	tab-to-tab-stop
	which-key-C-h-dispatch
	))

(setq mc/cmds-to-run-once
      '(
	))
